Us015 edit a role
anthony-raybould/bham1-back-end pull request #13
Opened 2023-09-19 11:15 UTC by RobertCrabtreeKainos

added endpoint for edit role.

2023-09-19 13:24 UTC, shaunganley requested changes
add validation with integration test and unit tests to cover

2023-09-19 13:24 UTC, shaunganley commented on .github/workflows/integration-test.yml
> +        run: mvn -B integration-test --file pom.xml
if you switch to using ENV VARs you wouldn't need to do this

2023-09-19 13:24 UTC, shaunganley commented on src/main/java/org/kainos/ea/api/JobRoleService.java
> +             if(jobRoleDao.updateJobRole(id, jobRoleRequest) == id){
shouldn't need this logic. I'm assuming you're returning the ID from the DAO just to check this? if an exception isn't thrown you can assume the call was successful

2023-09-19 13:24 UTC, shaunganley commented on src/main/java/org/kainos/ea/api/JobRoleService.java
> +        try{
need validation before calling DAO

2023-09-19 14:26 UTC, RobertCrabtreeKainos commented on .github/workflows/integration-test.yml
> +        run: mvn -B integration-test --file pom.xml
its outdated

2023-09-21 10:44 UTC, TomBillingtonUK commented on src/main/java/org/kainos/ea/api/JobRoleService.java
> +            return jobRoleDao.updateJobRole(id, jobRoleRequest);
You should probably make use of your validator.

2023-09-21 10:44 UTC, TomBillingtonUK commented on src/main/java/org/kainos/ea/db/JobRoleDao.java
> +            System.err.println("hi ho ");
it's not in the code you go

2023-09-21 10:44 UTC, TomBillingtonUK commented on src/main/java/org/kainos/ea/resources/BandController.java
> +            throw new RuntimeException(e);
For a SQL Exception, you should probably return a 500 error

2023-09-21 10:44 UTC, TomBillingtonUK commented on src/main/java/org/kainos/ea/resources/JobRoleController.java
> +    //@RolesAllowed("Admin")
Commented out annotation on this line and line 54

2023-09-21 10:44 UTC, TomBillingtonUK commented on src/main/java/org/kainos/ea/validator/UpdateJobRoleValidator.java
> +        if (jobRole.getSharePoint() == null || jobRole.getSharePoint().length() > 255) {
You probably want to validate this is a URL

2023-09-21 10:44 UTC, TomBillingtonUK commented on src/main/java/org/kainos/ea/validator/UpdateJobRoleValidator.java
> +        if (jobRole.getBand() == null || jobRole.getBand().getBandID() > 32767) {
For band and capability you probably want to check the value exists in the database as well as checking it's a number, so you return a 400 not a 500 back to the end user

2023-09-21 10:44 UTC, TomBillingtonUK commented on src/test/java/org/kainos/ea/dao/BandDaoTest.java
> +public class BandDaoTest {
Missing test case:
-> On DB error SQL Exception is thrown

2023-09-21 10:44 UTC, TomBillingtonUK commented on src/test/java/org/kainos/ea/dao/CapabilityDaoTest.java
> +public class CapabilityDaoTest {
Missing test case:
-> On DB error SQL Exception is thrown

2023-09-21 10:44 UTC, TomBillingtonUK commented on src/test/java/org/kainos/ea/dao/JobRoleDaoTest.java
> +    public void updateJobRole_shouldReturnNegative1_whenCantUpdate() throws SQLException, FailedToUpdateJobRoleException {
Test Name Update -> It throws an exception not returning -1

2023-09-21 10:44 UTC, TomBillingtonUK commented on src/test/java/org/kainos/ea/integration/CapabilityIntegrationTest.java
> +    void band_shouldReturn200() {
Fix test name

2023-09-21 10:44 UTC, TomBillingtonUK commented on src/test/java/org/kainos/ea/integration/JobRoleIntegrationTest.java
> +        Response response = APP.client().target("http://localhost:8080" + "/api/job-roles/1")
Should use TARGET_DOMAIN env var

2023-09-21 10:44 UTC, TomBillingtonUK commented on src/test/java/org/kainos/ea/integration/JobRoleIntegrationTest.java
> +    void updateJobRoles_shouldReturn500_whenNullBody() {
Test says should return 500 but it checks for a 400

2023-09-21 10:44 UTC, TomBillingtonUK commented on src/test/java/org/kainos/ea/service/CapabilityServiceTests.java
> +public class CapabilityServiceTests {
Fix test names in this file as they say bands

2023-09-25 10:02 UTC, TomBillingtonUK commented on src/main/java/org/kainos/ea/validator/UpdateJobRoleValidator.java
> +    public boolean validate(UpdateJobRoleRequest jobRole)
The more information we give back to the API client, the easier for the consuming application to respond. I suggest tweaking this validation so the user receives more detailed validation messages.

1. Change this method to void but throw a Validation Exception
2. When validation fails throw the Validation Exception with the reason why the validation failed (the if condition in English)
3. Update the service class to throw the Validation Exception and the if checking if validation was successful.

Hopefully that makes sense

2023-09-25 10:02 UTC, TomBillingtonUK commented on src/main/java/org/kainos/ea/db/JobRoleDao.java
> +    public int updateJobRole(int id, UpdateJobRoleRequest jobRoleRequest) throws SQLException, FailedToUpdateJobRoleException {
An invalid foreign key will cause the application to return a 500 error when it should return a 400, as that is user input. Is there a way we can make sure the right responses are sent back to the consumer

2023-09-25 10:02 UTC, TomBillingtonUK commented on src/test/java/org/kainos/ea/dao/BandDaoTest.java
> +public class BandDaoTest {
> Missing test case: -> On DB error SQL Exception is thrown

Comment not addressed

2023-09-25 10:02 UTC, TomBillingtonUK commented on src/test/java/org/kainos/ea/dao/CapabilityDaoTest.java
> +public class CapabilityDaoTest {
> Missing test case: -> On DB error SQL Exception is thrown

Comment not addressed

2023-09-25 10:02 UTC, TomBillingtonUK commented on src/test/java/org/kainos/ea/service/CapabilityServiceTests.java
> +    public void getBands_shouldReturnCapabilities_whenSuccess() throws SQLException, FailedToGetCapabilitiesException {
Test name:
`getCapabilities_shouldReturnCapabilities_whenSuccess()`

2023-09-25 10:02 UTC, TomBillingtonUK commented on src/test/java/org/kainos/ea/service/CapabilityServiceTests.java
> +    public void getBands_shouldThrowFailedToGetCapabilityException_whenSQLException() throws SQLException {
Test name:
`getCapabilities_shouldThrowFailedToGetCapabilityException_whenSQLException`

2023-09-25 10:02 UTC, TomBillingtonUK commented on src/test/java/validator/UpdateJobRoleValidatorTests.java
> +    @ParameterizedTest
👍  Nice use of this to avoid duplicating the test

2023-09-25 14:20 UTC, TomBillingtonUK approved these changes

2023-09-27 08:32 UTC, LMBishop approved these changes

2023-09-27 13:30 UTC, merged